### ISSUE TITLE
Explicitly clarify the license terms

### ISSUE THREAD

**Issue by jserv** [x213212/mini-riscv-os-vga#1]
This project was derived from [mini-riscv-os](https://github.com/cccriscv/mini-riscv-os), redistributable under the two-clause BSD License:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

However, no license terms appear in current repository, preventing it from be compliant with BSD License.

**Comment by x213212** [comment]
Jserv大神路過,感謝已補
